workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      node: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install @capacitor/core @capacitor/cli @capacitor/android
      - name: Build web assets
        script: |
          npm run build
      - name: Configure and Sync Android
        script: |
          # إنشاء المجلد الوهمي ونقل الملفات إليه لتخطي خطأ المسار
          mkdir -p www
          cp -r dist/* www/
          
          if [ ! -d "android" ]; then
            npx cap init apper2 io.codemagic.android --web-dir=www
            npx cap add android
          fi
          
          npx cap sync android
      - name: Build Android package
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/**/*.apk
